### ISSUE TITLE
hi where is  I3D/experiments/dataset/ along with the train.py and test.py.

### ISSUE THREAD

**Issue by senlin-ali** [didpurwanto/feat_visualization#1]

**Comment by didpurwanto** [comment]
To visualize the features, you should have your finetuned model first. For train.py and test.py, you can refer to I3D tensorflow 
[https://github.com/LossNAN/I3D-Tensorflow/tree/master/experiments/hmdb-51](url)

For dataset, you can use UCF-101 or HMDB-51 dataset. Note, you need to extract those videos into frame level. For easy reference, you can refer to [https://github.com/LossNAN/I3D-Tensorflow/blob/master/list/ucf_list/convert_images_to_list.sh](url).
